name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: script/setup
      - run: script/build
      # - run: script/test --chrome
      - run: script/deploy
        if: github.ref == 'refs/heads/master'
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
