name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup
        run: script/setup
      - name: Build
        run: script/build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          branch: main
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: poxels
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        id: publish
      - name: Deployment URL
        run: echo "${{ steps.publish.outputs.url }}"
